import Head from "next/head";
import Footer from "../Footer";
import { ILayout } from "./interface";

const Layout = ({ children, title }: ILayout) => (
  <>
    <Head>
      <title>{title} • Next Studies • Helena Martins</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main style={{ minHeight: "90vh" }}>{children}</main>
    <Footer />
  </>
);

export default Layout;
